name: Korean Stock Monitor

on:
  schedule:
    # KST 10:00 → UTC 01:00 (월~금)
    - cron: '0 1 * * 1-5'
    # KST 14:50 → UTC 05:50 (월~금)
    - cron: '50 5 * * 1-5'
  workflow_dispatch:

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Stock monitor
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:  ${{ secrets.TELEGRAM_CHAT_ID }}
          DART_API_KEY:       ${{ secrets.DART_API_KEY }}
          STOCK_LIST:        ${{ secrets.STOCK_LIST }}
          SCALE_MACD:        ${{ secrets.SCALE_MACD }}
          SAVE_CSV:          ${{ secrets.SAVE_CSV }}
          FONT_PATH:         'fonts/NanumGothic.ttf'
        run: python main.py
